{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import pymysql as p\n",
    "import tkinter as t\n",
    "from tkinter import *\n",
    "from tkinter import messagebox\n",
    "import cv2\n",
    "from PIL import Image,ImageTk "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "#project registration page\n",
    "def welcome_page():\n",
    "    #Web Page\n",
    "    root=t.Tk()\n",
    "    root.title(\"A Team\")\n",
    "    root.geometry('1360x1280')\n",
    "    root.configure(bg='light grey')\n",
    "    \n",
    "    canvas = Canvas(root,width=1360,height=1080)\n",
    "    canvas.pack()\n",
    "    my_image=PhotoImage(file='C:\\\\Users\\\\md shahid ahmad\\\\Downloads\\\\background.gif',master=root)\n",
    "    canvas.create_image(720,320,anchor=CENTER,image=my_image)\n",
    " \n",
    "    #Welcome page\n",
    "    welcome=t.Label(root,text=\"---   WELCOME TO Genquie India   ---\",font=('ALGERIAN',45),bg='light grey',fg='blue')\n",
    "    welcome.place(x=220,y=100)\n",
    "    \n",
    "    \n",
    "    slog=t.Label(root,text=\"---* A DESIRE FOR SUCCESS ENDS HERE  *---\",font=('Chaparral Pro Light',40),fg='blue')\n",
    "    slog.place(x=240,y=640)\n",
    "    \n",
    "    #signup\n",
    "    signupbutton=t.Button(root,text=\"SignUp\",font=('Times New Roman',22),command=signup,fg='red',bg='light grey')\n",
    "    signupbutton.place(x=440,y=400)\n",
    "    \n",
    "    #login\n",
    "    loginbutton=t.Button(root,text=\"LogIn\",font=('Times New Roman',22),command=login,fg='red',bg='light grey')\n",
    "    loginbutton.place(x=790,y=400)\n",
    "    \n",
    "    \n",
    "    root.mainloop() #closing the root loop\n",
    "    \n",
    "    \n",
    "def login():\n",
    "    #login page\n",
    "    loginmain=t.Tk()\n",
    "    loginmain.title('Login page')\n",
    "    loginmain.geometry('1920x1080')\n",
    "    \n",
    "    canvas = Canvas(loginmain,width=1280,height=1080)\n",
    "    canvas.pack()\n",
    "    my_image=PhotoImage(file='C:\\\\Users\\\\md shahid ahmad\\\\Downloads\\\\logbg.gif',master=loginmain)\n",
    "    canvas.create_image(700,300,anchor=CENTER,image=my_image)\n",
    " \n",
    "    \n",
    "        \n",
    "    #login label\n",
    "    \n",
    "    logintext=t.Label(loginmain,text=\"Username\",font=('Times New Roman',18),bg='light blue')\n",
    "    logintext.place(x=615,y=200)\n",
    "    \n",
    "    #login entry field\n",
    "    \n",
    "    global l_us_ent\n",
    "    l_us_ent=t.Entry(loginmain)\n",
    "    l_us_ent.place(x=570,y=245,width=210,height=30)\n",
    "    \n",
    "    #password field\n",
    "    \n",
    "    keytxt=t.Label(loginmain,text=\"Password\",font=('Times New Roman',18),bg='light blue')\n",
    "    keytxt.place(x=620,y=310)\n",
    "    \n",
    "    #password entry\n",
    "    \n",
    "    global l_pas_ent\n",
    "    l_pas_ent=t.Entry(loginmain,show='*')\n",
    "    l_pas_ent.place(x=570,y=355,width=210,height=30)\n",
    "    \n",
    "    #Login Button\n",
    "    \n",
    "    logbut=t.Button(loginmain,text=\"LogIn\",bg='light blue',font=('Edwardian Script ITC',25),command=user_valid)\n",
    "    logbut.place(x=610,y=420,width=110,height=30)\n",
    "    \n",
    "    \n",
    "    loginmain.mainloop() #closing the main loop\n",
    "def signup():\n",
    "    #signup page\n",
    "    signmain=t.Tk()\n",
    "    signmain.title('sign page')\n",
    "    signmain.geometry('1360x1080')\n",
    "    \n",
    "    #image of sign up\n",
    "    canvas = Canvas(signmain,width=1360,height=1080)\n",
    "    canvas.pack()\n",
    "    my_image=PhotoImage(file='C:\\\\Users\\\\md shahid ahmad\\\\Downloads\\\\signupbg.gif',master=signmain)\n",
    "    canvas.create_image(720,320,anchor=CENTER,image=my_image)\n",
    " \n",
    "    #create an account\n",
    "      \n",
    "    a=t.Label(signmain,text=\"Create an Account\",font=('Chaparral Pro Light',40))\n",
    "    a.place(x=700,y=30)\n",
    "    \n",
    "    \n",
    "    b=t.Label(signmain,text=\"It's free and always will be.\",font=('Calibri (Body)',13))\n",
    "    b.place(x=705,y=118)\n",
    "        \n",
    "    #username label\n",
    "    \n",
    "    us_nm=t.Label(signmain,text=\"Username\",font=('Times New Roman',15))\n",
    "    us_nm.place(x=710,y=160)\n",
    "    \n",
    "    #username entry field\n",
    "    \n",
    "    global s_us_ent\n",
    "    s_us_ent=t.Entry(signmain)\n",
    "    s_us_ent.place(x=840,y=160,width=210,height=30)\n",
    "    \n",
    "    #password field\n",
    "    \n",
    "    key1txt=t.Label(signmain,text=\"Password\",font=('Times New Roman',15))\n",
    "    key1txt.place(x=710,y=200)\n",
    "    \n",
    "    #password entry\n",
    "    \n",
    "    global spas1_ent\n",
    "    spas1_ent=t.Entry(signmain)\n",
    "    spas1_ent.place(x=840,y=200,width=210,height=30)\n",
    "    \n",
    "    #re-password field\n",
    "    \n",
    "    key1txt=t.Label(signmain,text=\"Re-Password\",font=('Times New Roman',15))\n",
    "    key1txt.place(x=710,y=240)\n",
    "    \n",
    "    #re-password entry\n",
    "    \n",
    "    global srepas_ent\n",
    "    srepas_ent=t.Entry(signmain)\n",
    "    srepas_ent.place(x=840,y=240,width=210,height=30)\n",
    " \n",
    "    #email\n",
    "    \n",
    "    ema=t.Label(signmain,text=\"Email\",font=('Times New Roman',15))\n",
    "    ema.place(x=710,y=280)\n",
    "    \n",
    "    #email entry\n",
    "    \n",
    "    global eme\n",
    "    eme=t.Entry(signmain)\n",
    "    eme.place(x=840,y=280,width=210,height=30)\n",
    "    \n",
    "    #gender \n",
    "    \n",
    "    gen=t.Label(signmain,text=\"Gender\",font=('Times New Roman',15))\n",
    "    gen.place(x=710,y=320)\n",
    "    \n",
    "    #Gender entry\n",
    "    \n",
    "    global gene\n",
    "    gene=t.IntVar(signmain)\n",
    "    m=t.Radiobutton(signmain,text='Male',font=('Georgia',13),value=1,variable=gene)\n",
    "    m.place(x=840,y=320)\n",
    "    n=t.Radiobutton(signmain,text='Female',font=('Georgia',13),value=2,variable=gene)\n",
    "    n.place(x=930,y=320)\n",
    "    \n",
    "    #phone\n",
    "    \n",
    "    mob=t.Label(signmain,text=\"Mobile Number\",font=('Times New Roman',15))\n",
    "    mob.place(x=710,y=360)\n",
    "    \n",
    "    #phone entry\n",
    "    \n",
    "    global mobe\n",
    "    mobe=t.Entry(signmain)\n",
    "    mobe.place(x=860,y=360,width=210,height=30)\n",
    "    \n",
    "    #data policy\n",
    "    a=t.Label(signmain,text=\"By clicking Sign Up, you agree to our Terms, Data Policy and\",font=('Chaparral Pro Light',11))\n",
    "    a.place(x=710,y=430)\n",
    "    a=t.Label(signmain,text=\"Cookie Policy. You may receive SMS notifications from us and can opt out at any time.\",font=('Chaparral Pro Light',11))\n",
    "    a.place(x=710,y=460)\n",
    "    \n",
    "    #Signup Button\n",
    "    \n",
    "    signbut=t.Button(signmain,text=\"SignUp\",font=('Edwardian Script ITC',30),command=store,bg='light blue')\n",
    "    signbut.place(x=850,y=500,width=120,height=40)\n",
    "    signmain.mainloop() #closing the main loop\n",
    "\n",
    "#storing in data base\n",
    "\n",
    "def store():\n",
    "    uname=str(s_us_ent.get())\n",
    "    pwd=str(spas1_ent.get())\n",
    "    print(pwd)\n",
    "    repwd=str(srepas_ent.get())\n",
    "    print(repwd)\n",
    "    email=str(eme.get())\n",
    "    gen=str(gene.get())\n",
    "    mobile=int(mobe.get())\n",
    "    if(pwd==repwd):\n",
    "        try:\n",
    "            connection=p.connect(host='localhost',db='assign',user='root',password='root')\n",
    "            s=connection.cursor()\n",
    "            print(\"1\")\n",
    "            sql=\"insert into user1(username,password,email,gender,mobile) values('%s','%s','%s','%s','%d')\"%(uname,pwd,email,gen,mobile)\n",
    "            i=s.execute(sql)\n",
    "            connection.commit()\n",
    "            if(i==1):\n",
    "                login()\n",
    "            else:\n",
    "                print(\"data is not inserted\")\n",
    "                signup()\n",
    "        except Exception:\n",
    "            print(Exception.args())\n",
    "    else:\n",
    "        print(\"invalid\")\n",
    "        signup()\n",
    "    \n",
    "    \n",
    "def home():\n",
    "    work4main=t.Tk()\n",
    "    work4main.title('Test-page')\n",
    "    work4main.geometry('1280x1080')    \n",
    "    \n",
    "    #image of home\n",
    "    canvas = Canvas(work4main,width=1400,height=1080)\n",
    "    canvas.pack()\n",
    "    my_image=PhotoImage(file='C:\\\\Users\\\\md shahid ahmad\\\\Downloads\\\\homebg.gif',master=work4main)\n",
    "    canvas.create_image(690,330,anchor=CENTER,image=my_image)\n",
    " \n",
    "    a=t.Label(work4main,text=\"Genquie India\",font=('Chaparral Pro Light',38))\n",
    "    a.place(x=550,y=30)\n",
    "\n",
    "    gksub=t.Button(work4main,text=\"BEGIN TEST\",font=('CASTELLAR',17),bg='White',fg='red',command=gkwork)\n",
    "    gksub.place(x=280,y=140)\n",
    "    \n",
    "     \n",
    "    vpsub=t.Button(work4main,text=\"View Profile\",font=('CASTELLAR',17),bg='White',fg='red',command=view)\n",
    "    vpsub.place(x=620,y=140)\n",
    "    \n",
    "    \n",
    "    sosub=t.Button(work4main,text=\"Sign Out\",font=('CASTELLAR',13),bg='White',fg='red',command=welcome_page)\n",
    "    sosub.place(x=1180,y=15)\n",
    "    \n",
    "    \n",
    "    work4main.mainloop()\n",
    "\n",
    " \n",
    "def change_email1():\n",
    "    pwd=str(em1.get())\n",
    "    nemail=str(em3.get())\n",
    "    old_email=str(em2.get())\n",
    "    try:\n",
    "        connection=p.connect(host='localhost',db='assign',user='root',password='root')\n",
    "        s=connection.cursor()\n",
    "        print(\"1\")\n",
    "        sql=\"update  user1  set  email='\"+nemail+\"' where password='\"+pwd+\"'\" \n",
    "        ii=s.execute(sql)\n",
    "        print(ii)\n",
    "        if(ii==1):\n",
    "            home()\n",
    "        else:\n",
    "            change_email()\n",
    "    except:\n",
    "        print(\"not successs\")\n",
    "    \n",
    "def change_password1():\n",
    "    mobile=str(cp1.get())\n",
    "    pwd=str(cp2.get())\n",
    "    npwd=str(cp3.get())\n",
    "    try:\n",
    "        connection=p.connect(host='localhost',db='assign',user='root',password='root')\n",
    "        s=connection.cursor()\n",
    "        print(\"1\")\n",
    "        sql=\"update  user1  set  password='\"+npwd+\"' where mobile='\"+mobile+\"'\" \n",
    "        ii=s.execute(sql)\n",
    "        print(ii)\n",
    "        if(ii==1):\n",
    "            home()\n",
    "        else:\n",
    "            change_password()\n",
    "    except:\n",
    "        print(\"not successs\")\n",
    "    \n",
    "\n",
    "def user_valid():\n",
    "    global name\n",
    "    name=l_us_ent.get()\n",
    "    print(name)\n",
    "    pwd=l_pas_ent.get()\n",
    "    print(pwd)\n",
    "    try:\n",
    "        connection=p.connect(host='localhost',db='assign',user='root',password='root')\n",
    "        s=connection.cursor()\n",
    "        print(\"1\")\n",
    "        sql=\"select username,password,email,mobile  from user1 where username='\"+name+\"' and password='\"+pwd+\"'\" \n",
    "        ii=s.execute(sql)\n",
    "        data=s.fetchall()\n",
    "        print(ii)\n",
    "        global l\n",
    "        l=[]\n",
    "        for d in data:\n",
    "            for i in d:\n",
    "                l.append(i)\n",
    "        connection.commit()\n",
    "        if(ii==1):\n",
    "            print(\"success\")\n",
    "            home()\n",
    "        else:\n",
    "            print(\"data is not inserted\")\n",
    "            signup()\n",
    "    except Exception:\n",
    "        print(Exception.args())\n",
    "        \n",
    "\n",
    "    \n",
    "\n",
    "def view():\n",
    "    work5main=t.Tk()\n",
    "    work5main.title('Profile page')\n",
    "    work5main.geometry('1360x1080')\n",
    "    work5main.configure(bg='light blue')\n",
    "   \n",
    "    \n",
    "    up1=t.Label(work5main,text='Your Profile',font=('bold',20),width=(25),fg='blue',bg='light blue')\n",
    "    up1.place(x=500,y=100)\n",
    "    \n",
    "    uname=l[0]\n",
    "    upwd=l[1]\n",
    "    uemail=l[2]\n",
    "    umobile=l[3]\n",
    "    \n",
    "    t2=t.Label(work5main,text='User Name:',font=(10),bg='light blue')\n",
    "    t2.place(x=400,y=165)\n",
    "    \n",
    "    tt2=t.Label(work5main,text=uname,font=(10),bg='light blue')\n",
    "    tt2.place(x=500,y=165)\n",
    "    \n",
    "    t10=t.Button(work5main,text=\"Change-E-mail:\",font=('bold',15),bg='light blue',command=change_email)\n",
    "    t10.place(x=650,y=470)\n",
    "    \n",
    "    t11=t.Button(work5main,text=\"Change-Mobile No.\",font=('bold',15),bg='light blue',command=change_mobile)\n",
    "    t11.place(x=650,y=520)\n",
    "    \n",
    "    t12=t.Button(work5main,text=\"Sign Out\",font=('bold',15),bg='light blue',command=welcome_page)\n",
    "    t12.place(x=1250,y=30)\n",
    "    \n",
    "    \n",
    "    #password\n",
    "    \n",
    "    t4=t.Label(work5main,text='Password:',font=(10),bg='light blue')\n",
    "    t4.place(x=400,y=205)\n",
    "    \n",
    "    tt4=t.Label(work5main,text=upwd,font=(10),bg='light blue')\n",
    "    tt4.place(x=500,y=205)\n",
    "    \n",
    "    #email\n",
    "    \n",
    "    t5=t.Label(work5main,text=\"E-mail:\",font=(10),bg='light blue')\n",
    "    t5.place(x=400,y=245)\n",
    "    \n",
    "    tt5=t.Label(work5main,text=uemail,font=(10),bg='light blue')\n",
    "    tt5.place(x=500,y=245)\n",
    "    \n",
    "    #phone\n",
    "    t6=t.Label(work5main,text=\"Mobile No.\",font=(10),bg='light blue')\n",
    "    t6.place(x=400,y=285)\n",
    "    \n",
    "    tt6=t.Label(work5main,text=umobile,font=(10),bg='light blue')\n",
    "    tt6.place(x=500,y=285)\n",
    "    \n",
    "    #for changinf the password\n",
    "    bt1=t.Button(work5main,text=\"Change password\",font=('bold',15),bg='light blue',command=change_password)\n",
    "    bt1.place(x=650,y=420)\n",
    "    \n",
    "    e1=t.Label(work5main,bg='light blue',text=\"..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................\")\n",
    "    e1.place(x=0,y=70)\n",
    "    \n",
    "    sb7=t.Button(work5main,text=\"Home\",font=(\"bold\",15),width=(8),bg=\"light blue\",command=home)\n",
    "    sb7.place(x=620,y=20)\n",
    "    \n",
    "    work5main.mainloop()\n",
    "    \n",
    "def change_password():\n",
    "    cange=t.Tk()\n",
    "    cange.geometry('1380x1080')\n",
    "    cange.resizable(width=True,height=True)\n",
    "    cange.configure(bg='light blue')\n",
    "    \n",
    "    t1=t.Button(cange,text=\"Sign-Out\",font=(10),bg='light blue',command=welcome_page)\n",
    "    t1.place(x=1200,y=20)\n",
    "    \n",
    "    e1=t.Label(cange,bg='light blue',text=\"..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................\")\n",
    "    e1.place(x=0,y=70)\n",
    "    \n",
    "    q1=t.Label(cange,text=\"Change password\",font=('bold',35),width=(25),fg=\"blue\",bg='light blue')\n",
    "    q1.place(x=350,y=20)\n",
    "   \n",
    "    \n",
    "    t1=t.Label(cange,text=\"Mobile\",font=(10),bg='light blue')\n",
    "    t1.place(x=400,y=165)\n",
    "    \n",
    "    global cp1\n",
    "    cp1=t.Entry(cange)\n",
    "    cp1.place(x=600,y=171)\n",
    "    \n",
    "    #password\n",
    "    t1=t.Label(cange,text=\"Password:\",font=(10),bg='light blue')\n",
    "    t1.place(x=400,y=205)\n",
    "    \n",
    "    global cp2\n",
    "    cp2=t.Entry(cange)\n",
    "    cp2.place(x=600,y=211)\n",
    "    \n",
    "    #repasswordt1\n",
    "    t1=t.Label(cange,text=\"Re-password\",font=(10),bg='light blue')\n",
    "    t1.place(x=400,y=245)\n",
    "    \n",
    "    global cp3\n",
    "    cp3=t.Entry(cange)\n",
    "    cp3.place(x=600,y=245)\n",
    "    \n",
    "    t1=t.Label(cange,text=\"\")\n",
    "    t1.place(x=1,y=60)\n",
    "    \n",
    "    cb1=t.Button(cange,text=\"Submit\",font=('bold',15),width=(8),bg='light blue',command=change_password1)\n",
    "    cb1.place(x=500,y=330)\n",
    "    \n",
    "    cange.mainloop()\n",
    "\n",
    "def change_email():\n",
    "    email=t.Tk()\n",
    "    email.geometry('1380x1080')\n",
    "    email.resizable(width=True,height=True)\n",
    "    email.configure(bg='light blue')\n",
    "    \n",
    "    t1=t.Button(email,text=\"Sign-Out\",font=('Edwardian Script ITC',18),bg='light blue',command=welcome_page)\n",
    "    t1.place(x=1200,y=20)\n",
    "    \n",
    "    q1=t.Label(email,text=\"Change Email\",font=('bold',35),width=(25),fg=\"blue\",bg='light blue')\n",
    "    q1.place(x=350,y=20)\n",
    "   \n",
    "    #password\n",
    "    t1=t.Label(email,text=\"Password\",font=(10),bg='light blue')\n",
    "    t1.place(x=400,y=165)\n",
    "    \n",
    "    global em1\n",
    "    em1=t.Entry(email)\n",
    "    em1.place(x=600,y=171)\n",
    "    \n",
    "    #email old\n",
    "    t1=t.Label(email,text=\"Old email\",font=(10),bg='light blue')\n",
    "    t1.place(x=400,y=205)\n",
    "    \n",
    "    global em2\n",
    "    em2=t.Entry(email)\n",
    "    em2.place(x=600,y=211)\n",
    "    \n",
    "    # new email\n",
    "    t1=t.Label(email,text=\"new email\",font=(10),bg='light blue')\n",
    "    t1.place(x=400,y=245)\n",
    "    \n",
    "    global em3\n",
    "    em3=t.Entry(email)\n",
    "    em3.place(x=600,y=245)\n",
    "    \n",
    "    t1=t.Label(email,text=\"\")\n",
    "    t1.place(x=1,y=60)\n",
    "    \n",
    "    ce1=t.Button(email,text=\"Submit\",font=('Edwardian Script ITC',23),width=(7),bg='light blue',command=change_email1)\n",
    "    ce1.place(x=500,y=290)\n",
    "    \n",
    "    email.mainloop()\n",
    "\n",
    "def change_mobile():\n",
    "    cmob=t.Tk()\n",
    "    cmob.geometry('1380x1080')\n",
    "    cmob.resizable(width=True,height=True)\n",
    "    cmob.configure(bg='light blue')\n",
    "    t1=t.Button(cmob,text=\"Sign-Out\",font=(10),bg='light blue')\n",
    "    t1.place(x=1200,y=20)\n",
    "    \n",
    "    q1=t.Label(cmob,text=\"Change mobile\",font=('bold',35),width=(25),fg=\"blue\",bg='light blue')\n",
    "    q1.place(x=350,y=20)\n",
    "   \n",
    "    \n",
    "    t1=t.Label(cmob,text=\"password\",font=(10),bg='light blue')\n",
    "    t1.place(x=400,y=165)\n",
    "    \n",
    "    global cm1\n",
    "    cp1=t.Entry(cmob)\n",
    "    cp1.place(x=600,y=171)\n",
    "    \n",
    "    #password\n",
    "    t1=t.Label(cmob,text=\"old mobile\",font=(10),bg='light blue')\n",
    "    t1.place(x=400,y=205)\n",
    "    \n",
    "    global cm2\n",
    "    cp2=t.Entry(cmob)\n",
    "    cp2.place(x=600,y=211)\n",
    "    \n",
    "    #repasswordt1\n",
    "    t1=t.Label(cmob,text=\"New mobile\",font=(10),bg='light blue')\n",
    "    t1.place(x=400,y=245)\n",
    "    \n",
    "    global cp3\n",
    "    cp3=t.Entry(cmob)\n",
    "    cp3.place(x=600,y=245)\n",
    "    \n",
    "    t1=t.Label(cmob,text=\"\")\n",
    "    t1.place(x=1,y=60)\n",
    "    \n",
    "    cb1=t.Button(cmob,text=\"Submit\",font=('bold',15),width=(8),bg='light blue')\n",
    "    cb1.place(x=500,y=290)\n",
    "    \n",
    "    cmob.mainloop()\n",
    "\n",
    "    \n",
    "\n",
    "def gkwork():   \n",
    "    workmain=t.Tk()\n",
    "    workmain.title('Test-page')\n",
    "    workmain.geometry('1360x1080')\n",
    "    \n",
    "    #qustion first\n",
    "    \n",
    "    \n",
    "    q1=t.Label(workmain,text=\" A) Who has been appointed as the new governer of Reserve Bank of India ?\",font=('Arial',15))\n",
    "    q1.place(x=13,y=20)\n",
    "    \n",
    "    a1=t.Label(workmain,text='1. John Josheph',font=('Georgia',15))\n",
    "    a1.place(x=30,y=60)\n",
    "    \n",
    "    a2=t.Label(workmain,text='2. Vanaja N.Sharma',font=('Georgia',15))\n",
    "    a2.place(x=220,y=60)\n",
    "    \n",
    "    a3=t.Label(workmain,text='3. S Ramesh',font=('Georgia',15))\n",
    "    a3.place(x=440,y=60)\n",
    "    \n",
    "    a4=t.Label(workmain,text='4. Shakti Kanta Das',font=('Georgia',15))\n",
    "    a4.place(x=600,y=60)\n",
    "    \n",
    "    global ra1\n",
    "    ra1=t.Entry(workmain)\n",
    "    ra1.place(x=860,y=60,height=35,width=60)\n",
    "    \n",
    "    #second qustion\n",
    "    \n",
    "    q2=t.Label(workmain,text=\" B) Who has been appointed as the acting chairman of the Union Public Service Commision (UPSC) ?\",font=('Arial',15))\n",
    "    q2.place(x=13,y=110)\n",
    "    \n",
    "    \n",
    "    a21=t.Label(workmain,text='1.Arvind Saxena',font=('Georgia',15))\n",
    "    a21.place(x=30,y=150)\n",
    "    \n",
    "    a22=t.Label(workmain,text='2.Sudha Jain',font=('Georgia',15))\n",
    "    a22.place(x=220,y=150)\n",
    "    \n",
    "    a23=t.Label(workmain,text='3.Kriti Kumar',font=('Georgia',15))\n",
    "    a23.place(x=440,y=150)\n",
    "    \n",
    "    a24=t.Label(workmain,text='4.Omi Agrawal ',font=('Georgia',15))\n",
    "    a24.place(x=600,y=150)\n",
    "    \n",
    "    global ra2\n",
    "    ra2=t.Entry(workmain)\n",
    "    ra2.place(x=860,y=150,height=35,width=60)\n",
    "    #third question\n",
    "    \n",
    "    q3=t.Label(workmain,text=\" C) Who is the current Prime Minister of Russia?\" ,font=('Arial',15))\n",
    "    q3.place(x=13,y=200)\n",
    "    \n",
    "    \n",
    "    a31=t.Label(workmain,text='1. Dmitry Modreder',font=('Georgia',15))\n",
    "    a31.place(x=30,y=240)\n",
    "    \n",
    "    a32=t.Label(workmain,text='2. Vladimir Putin',font=('Georgia',15))\n",
    "    a32.place(x=240,y=240)\n",
    "    \n",
    "    a33=t.Label(workmain,text='3. Alexei Naralny',font=('Georgia',15))\n",
    "    a33.place(x=440,y=240)\n",
    "    \n",
    "    a34=t.Label(workmain,text='4. Sretlana Medredva',font=('Georgia',15))\n",
    "    a34.place(x=615,y=240)\n",
    "    global ra3\n",
    "    ra3=t.Entry(workmain)\n",
    "    ra3.place(x=860,y=240,height=35,width=60)\n",
    "    \n",
    "    #fourth qustion\n",
    "    \n",
    "    q4=t.Label(workmain,text=\" D) India's first ever national police museum will establish in which City ?\" ,font=('Arial',15))\n",
    "    q4.place(x=13,y=295)\n",
    "    \n",
    "    \n",
    "    a41=t.Label(workmain,text='1. Chennai',font=('Georgia',15))\n",
    "    a41.place(x=30,y=340)\n",
    "    \n",
    "    a42=t.Label(workmain,text='2. Delhi',font=('Georgia',15))\n",
    "    a42.place(x=170,y=340)\n",
    "    \n",
    "    a43=t.Label(workmain,text='3. Nagpur',font=('Georgia',15))\n",
    "    a43.place(x=280,y=340)\n",
    "    \n",
    "    a44=t.Label(workmain,text='4. Kolkata',font=('Georgia',15))\n",
    "    a44.place(x=400,y=340)\n",
    "    global ra4\n",
    "    ra4=t.Entry(workmain)\n",
    "    ra4.place(x=860,y=340,height=35,width=60)\n",
    "    \n",
    "    #five question\n",
    "              \n",
    "    q5=t.Label(workmain,text=\" E)  Which country will host the 45th G7 summit 2019 ?\" ,font=('Arial',15))\n",
    "    q5.place(x=13,y=390)\n",
    "    \n",
    "    \n",
    "    a51=t.Label(workmain,text='1. Italy',font=('Georgia',15))\n",
    "    a51.place(x=30,y=430)\n",
    "    \n",
    "    a52=t.Label(workmain,text='2. Germany',font=('Georgia',15))\n",
    "    a52.place(x=140,y=430)\n",
    "    \n",
    "    a53=t.Label(workmain,text='3. France',font=('Georgia',15))\n",
    "    a53.place(x=280,y=430)\n",
    "    \n",
    "    a54=t.Label(workmain,text='4. Canada',font=('Georgia',15))\n",
    "    a54.place(x=400,y=430)       \n",
    "    global ra5\n",
    "    ra5=t.Entry(workmain)\n",
    "    ra5.place(x=860,y=430,height=35,width=60)\n",
    "    \n",
    "    #six question\n",
    "    q6=t.Label(workmain,text=\" F) Which country woman's cricket team has this Asia cup t20 ?\" ,font=('Arial',15))\n",
    "    q6.place(x=13,y=490)\n",
    "    \n",
    "    a61=t.Label(workmain,text='1. Pakistan',font=('Georgia',15))\n",
    "    a61.place(x=30,y=530)\n",
    "    \n",
    "    a62=t.Label(workmain,text='2. India',font=('Georgia',15))\n",
    "    a62.place(x=150,y=530)\n",
    "    \n",
    "    a63=t.Label(workmain,text='3. Bangladesh',font=('Georgia',15))\n",
    "    a63.place(x=265,y=530)\n",
    "    \n",
    "    a64=t.Label(workmain,text='4. Sri-Lanka',font=('Georgia',15))\n",
    "    a64.place(x=430,y=530) \n",
    "    global ra6\n",
    "    ra6=t.Entry(workmain)\n",
    "    ra6.place(x=860,y=530,height=35,width=60)    \n",
    "    \n",
    "    #seven question\n",
    "    q7=t.Label(workmain,text=\" G) Which country's football team has lifted the 2018 Intercontinential Cup football title ?\" ,font=('Arial',15))\n",
    "    q7.place(x=13,y=610)\n",
    "    \n",
    "    a71=t.Label(workmain,text='1. India',font=('Georgia',15))\n",
    "    a71.place(x=30,y=660)\n",
    "    \n",
    "    a72=t.Label(workmain,text='2. Sri Lanka',font=('Georgia',15))\n",
    "    a72.place(x=130,y=660)\n",
    "    \n",
    "    a73=t.Label(workmain,text='3. Kenya',font=('Georgia',15))\n",
    "    a73.place(x=275,y=660)\n",
    "    \n",
    "    a74=t.Label(workmain,text='4. Argentina',font=('Georgia',15))\n",
    "    a74.place(x=400,y=660) \n",
    "    global ra7\n",
    "    ra7=t.Entry(workmain)\n",
    "    ra7.place(x=860,y=660,height=35,width=60)    \n",
    "    \n",
    "    #gkwork submit\n",
    "    \n",
    "    gksub=t.Button(workmain,text=\"Submit\",font=('Chaparral Pro Light',22),command=clickme)\n",
    "    gksub.place(x=1100,y=600)\n",
    "    \n",
    "    workmain.mainloop()\n",
    "\n",
    "def clickme():\n",
    "    messagebox.showinfo(\"SUBMIT\",'CHECKING YOUR RESULT FOR NEXT TEST IF PASS NEXT TEST IS STARTED AND FAIL AUTOMATIVALLY GO FOR LOGIN PAGE')\n",
    "    gvalid()\n",
    "    \n",
    "def gvalid():\n",
    "    qu1=int(ra1.get())\n",
    "    print(qu1)\n",
    "    qu2=int(ra2.get())\n",
    "    print(qu2)\n",
    "    qu3=int(ra3.get())\n",
    "    print(qu3)\n",
    "    qu4=int(ra4.get())\n",
    "    print(qu4)\n",
    "    qu5=int(ra5.get())\n",
    "    print(qu5)\n",
    "    qu6=int(ra6.get())\n",
    "    print(qu6)\n",
    "    qu7=int(ra7.get())\n",
    "    print(qu7)\n",
    "    count=0\n",
    "    if(qu1==4):\n",
    "        count+=1\n",
    "    if(qu2==1):\n",
    "        count+=1\n",
    "    if(qu3==1):\n",
    "        count+=1\n",
    "    if(qu4==2):\n",
    "        count+=1\n",
    "    if(qu5==3):\n",
    "        count+=1\n",
    "    if(qu6==3):\n",
    "        count+=1\n",
    "    if(qu7==1):\n",
    "        count+=1\n",
    "    if(count>4):\n",
    "        print(\"Pass\")\n",
    "        mtwork()\n",
    "    else:\n",
    "        print(\"fail\")\n",
    "        login()\n",
    "    print(count)\n",
    "    \n",
    "def mtwork(): \n",
    "    work2main=t.Tk()\n",
    "    work2main.title('Test-page')\n",
    "    work2main.geometry('1360x1080')\n",
    "    \n",
    "    #qustion first\n",
    "    \n",
    "    \n",
    "    mq1=t.Label(work2main,text=\" A) The average of first 50 Natural number is ?\",font=('Arial',15))\n",
    "    mq1.place(x=13,y=20)\n",
    "    \n",
    "    global mt1\n",
    "    mt1=t.Entry(work2main)\n",
    "    mt1.place(x=800,y=60,height=35,width=60)\n",
    "    \n",
    "    ma1=t.Label(work2main,text='1. 25.30',font=('Georgia',15))\n",
    "    ma1.place(x=30,y=60)\n",
    "    \n",
    "    ma2=t.Label(work2main,text='2. 25.5',font=('Georgia',15))\n",
    "    ma2.place(x=160,y=60)\n",
    "    \n",
    "    ma3=t.Label(work2main,text='3. 25.00',font=('Georgia',15))\n",
    "    ma3.place(x=300,y=60)\n",
    "    \n",
    "    ma4=t.Label(work2main,text='4. 12.25',font=('Georgia',15))\n",
    "    ma4.place(x=440,y=60)\n",
    "    \n",
    "    #second qustion\n",
    "    \n",
    "    mq2=t.Label(work2main,text=\" B) A fraction which bears the same to 1/27 as 3/11 bear to 5/9 is ?\" ,font=('Arial',15))\n",
    "    mq2.place(x=13,y=110)\n",
    "    \n",
    "    global mt2\n",
    "    mt2=t.Entry(work2main)\n",
    "    mt2.place(x=800,y=150,height=35,width=60)\n",
    "    \n",
    "    ma21=t.Label(work2main,text='1. 1/55',font=('Georgia',15))\n",
    "    ma21.place(x=30,y=150)\n",
    "    \n",
    "    ma22=t.Label(work2main,text='2. 55',font=('Georgia',15))\n",
    "    ma22.place(x=190,y=150)\n",
    "    \n",
    "    ma23=t.Label(work2main,text='3. 3/11',font=('Georgia',15))\n",
    "    ma23.place(x=370,y=150)\n",
    "    \n",
    "    ma24=t.Label(work2main,text='4. 1/11 ',font=('Georgia',15))\n",
    "    ma24.place(x=550,y=150)\n",
    "    \n",
    "    #third qustion\n",
    "    \n",
    "    mq3=t.Label(work2main,text=\" C) The number of 3-digit number divisible by 6 is\" ,font=('Arial',15))\n",
    "    mq3.place(x=13,y=200)\n",
    "    \n",
    "    global mt3\n",
    "    mt3=t.Entry(work2main)\n",
    "    mt3.place(x=800,y=240,height=35,width=60)\n",
    "    \n",
    "    ma31=t.Label(work2main,text='1. 149',font=('Georgia',15))\n",
    "    ma31.place(x=30,y=240)\n",
    "    \n",
    "    ma32=t.Label(work2main,text='2. 166',font=('Georgia',15))\n",
    "    ma32.place(x=170,y=240)\n",
    "    \n",
    "    ma33=t.Label(work2main,text='3. 150',font=('Georgia',15))\n",
    "    ma33.place(x=280,y=240)\n",
    "    \n",
    "    ma34=t.Label(work2main,text='4. 151',font=('Georgia',15))\n",
    "    ma34.place(x=380,y=240)\n",
    "    \n",
    "    #fourth qustion\n",
    "    \n",
    "    mq4=t.Label(work2main,text=\" D) What is 1004 divided by 2\" ,font=('Arial',15))\n",
    "    mq4.place(x=13,y=295)\n",
    "    \n",
    "    global mt4\n",
    "    mt4=t.Entry(work2main)\n",
    "    mt4.place(x=800,y=340,height=35,width=60)\n",
    "    \n",
    "    ma41=t.Label(work2main,text='1. 52',font=('Georgia',15))\n",
    "    ma41.place(x=30,y=340)\n",
    "    \n",
    "    ma42=t.Label(work2main,text='2. 502',font=('Georgia',15))\n",
    "    ma42.place(x=170,y=340)\n",
    "    \n",
    "    ma43=t.Label(work2main,text='3. 520',font=('Georgia',15))\n",
    "    ma43.place(x=330,y=340)\n",
    "    \n",
    "    ma44=t.Label(work2main,text='4. 5002',font=('Georgia',15))\n",
    "    ma44.place(x=480,y=340)\n",
    "    \n",
    "    #five question\n",
    "              \n",
    "    mq5=t.Label(work2main,text=\" E) A clock strikes once at 1'O'clock, twice at 2'O' clock, thrice at 3'O' colock and so on. How many times will it strike in 24 hrs?\" ,font=('Arial',15))\n",
    "    mq5.place(x=13,y=390)\n",
    "    \n",
    "    global mt5\n",
    "    mt5=t.Entry(work2main)\n",
    "    mt5.place(x=800,y=430,height=35,width=60)\n",
    "    \n",
    "    ma51=t.Label(work2main,text='1. 78',font=('Georgia',15))\n",
    "    ma51.place(x=30,y=430)\n",
    "    \n",
    "    ma52=t.Label(work2main,text='2. 136',font=('Georgia',15))\n",
    "    ma52.place(x=140,y=430)\n",
    "    \n",
    "    ma53=t.Label(work2main,text='3. 156',font=('Georgia',15))\n",
    "    ma53.place(x=280,y=430)\n",
    "    \n",
    "    ma54=t.Label(work2main,text='4. 196',font=('Georgia',15))\n",
    "    ma54.place(x=400,y=430)       \n",
    "    \n",
    "    #Six question\n",
    "    \n",
    "    mq6=t.Label(work2main,text=\" F) Solve: 106 X 106 - 94 X 94 \" ,font=('Arial',15))\n",
    "    mq6.place(x=13,y=490)\n",
    "    \n",
    "    global mt6\n",
    "    mt6=t.Entry(work2main)\n",
    "    mt6.place(x=800,y=550,height=35,width=60)\n",
    "    \n",
    "    ma61=t.Label(work2main,text='1. 2004',font=('Georgia',15))\n",
    "    ma61.place(x=30,y=550)\n",
    "    \n",
    "    ma62=t.Label(work2main,text='2. 2400',font=('Georgia',15))\n",
    "    ma62.place(x=140,y=550)\n",
    "    \n",
    "    ma63=t.Label(work2main,text='3. 1904',font=('Georgia',15))\n",
    "    ma63.place(x=280,y=550)\n",
    "    \n",
    "    ma64=t.Label(work2main,text='4. 1906',font=('Georgia',15))\n",
    "    ma64.place(x=400,y=550)     \n",
    "    \n",
    "    #seventh question\n",
    "    \n",
    "    mq7=t.Label(work2main,text=\" G) 20% of 2 is equal to \" ,font=('Arial',15))\n",
    "    mq7.place(x=13,y=610)\n",
    "    \n",
    "    global mt7\n",
    "    mt7=t.Entry(work2main)\n",
    "    mt7.place(x=800,y=660,height=35,width=60)\n",
    "    \n",
    "    \n",
    "    ma71=t.Label(work2main,text='1. 20',font=('Georgia',15))\n",
    "    ma71.place(x=30,y=660)\n",
    "    \n",
    "    ma72=t.Label(work2main,text='2. 4',font=('Georgia',15))\n",
    "    ma72.place(x=140,y=660)\n",
    "    \n",
    "    ma73=t.Label(work2main,text='3. 0.4',font=('Georgia',15))\n",
    "    ma73.place(x=280,y=660)\n",
    "    \n",
    "    ma74=t.Label(work2main,text='4. 0.04',font=('Georgia',15))\n",
    "    ma74.place(x=400,y=660)     \n",
    "    \n",
    "    \n",
    "\n",
    "    #Submit button\n",
    "    \n",
    "    submt=t.Button(work2main,text=\"SUBMIT TEST\",font=('Chaparral Pro Light',23),command=clickme1)\n",
    "    submt.place(x=1100,y=600)\n",
    "    \n",
    "    work2main.mainloop()\n",
    "\n",
    "def clickme1():\n",
    "    messagebox.showinfo(\"SUBMIT\",'CHECKING YOUR RESULT FOR NEXT TEST IF PASS NEXT TEST IS STARTED AND FAIL AUTOMATIVALLY GO FOR LOGIN PAGE')\n",
    "    gmtvalid()\n",
    "\n",
    "    \n",
    "def gmtvalid():\n",
    "    rmt1=int(mt1.get())\n",
    "    rmt2=int(mt2.get())\n",
    "    rmt3=int(mt3.get())\n",
    "    rmt4=int(mt4.get())\n",
    "    rmt5=int(mt5.get())\n",
    "    rmt6=int(mt6.get())\n",
    "    rmt7=int(mt7.get())\n",
    "    mcount=0\n",
    "    if(rmt1==2):\n",
    "        mcount+=1\n",
    "    if(rmt2==1):\n",
    "        mcount+=1\n",
    "    if(rmt3==3):\n",
    "        mcount+=1\n",
    "    if(rmt4==2):\n",
    "        mcount+=1\n",
    "    if(rmt5==3):\n",
    "        mcount+=1\n",
    "    if(rmt6==2):\n",
    "        mcount+=1\n",
    "    if(rmt7==3):\n",
    "        mcount+=1\n",
    "    if(mcount>4):\n",
    "        print(\"Pass\")\n",
    "        swork()\n",
    "    else:\n",
    "        print(\"fail\")\n",
    "        login()    \n",
    "\n",
    "def swork():\n",
    "    work3main=t.Tk()\n",
    "    work3main.title('Test-page')\n",
    "    work3main.geometry('1360x1080')\n",
    "    \n",
    "    #qustion first\n",
    "    \n",
    "    \n",
    "    wq1=t.Label(work3main,text=\"  A. The lens used in a simple microscope ?\",font=('Arial',15))\n",
    "    wq1.place(x=13,y=20)\n",
    "    \n",
    "    w11=t.Label(work3main,text='1. Concave',font=('Georgia',15))\n",
    "    w11.place(x=30,y=60)\n",
    "    \n",
    "    w12=t.Label(work3main,text='2. Canvex',font=('Georgia',15))\n",
    "    w12.place(x=160,y=60)\n",
    "    \n",
    "    w13=t.Label(work3main,text='3. Cylindrical',font=('Georgia',15))\n",
    "    w13.place(x=290,y=60)\n",
    "    \n",
    "    w14=t.Label(work3main,text='4. None',font=('Georgia',15))\n",
    "    w14.place(x=440,y=60)\n",
    "    \n",
    "    global s1\n",
    "    s1=t.Entry(work3main)\n",
    "    s1.place(x=800,y=60,width=60,height=35)\n",
    "    #second qustion\n",
    "    \n",
    "    wq2=t.Label(work3main,text=\"  B. The elimation of the toxic nitrogeneous waste and access water in man is by ?\" ,font=('Arial',15))\n",
    "    wq2.place(x=13,y=110)\n",
    "    \n",
    "    w21=t.Label(work3main,text='1. Excretion',font=('Georgia',15))\n",
    "    w21.place(x=30,y=150)\n",
    "    \n",
    "    w22=t.Label(work3main,text='2. Circulation',font=('Georgia',15))\n",
    "    w22.place(x=190,y=150)\n",
    "    \n",
    "    w23=t.Label(work3main,text='3. Reproduction',font=('Georgia',15))\n",
    "    w23.place(x=370,y=150)\n",
    "    \n",
    "    w24=t.Label(work3main,text='4. Pollution',font=('Georgia',15))\n",
    "    w24.place(x=550,y=150)\n",
    "    \n",
    "    global s2\n",
    "    s2=t.Entry(work3main)\n",
    "    s2.place(x=800,y=150,width=60,height=35)\n",
    "    \n",
    "    \n",
    "    \n",
    "    #third qustion\n",
    "    \n",
    "    wq3=t.Label(work3main,text=\"  C. The S.I unit of refraction Index is ?\" ,font=('Arial',15))\n",
    "    wq3.place(x=13,y=200)\n",
    "    \n",
    "    w31=t.Label(work3main,text='1. Meter',font=('Georgia',15))\n",
    "    w31.place(x=30,y=240)\n",
    "    \n",
    "    w32=t.Label(work3main,text='2. Cm',font=('Georgia',15))\n",
    "    w32.place(x=170,y=240)\n",
    "    \n",
    "    w33=t.Label(work3main,text='3. Watt',font=('Georgia',15))\n",
    "    w33.place(x=280,y=240)\n",
    "    \n",
    "    w44=t.Label(work3main,text='4. No unit',font=('Georgia',15))\n",
    "    w44.place(x=380,y=240)\n",
    "    \n",
    "    global s3\n",
    "    s3=t.Entry(work3main)\n",
    "    s3.place(x=800,y=240,width=60,height=35)\n",
    "    \n",
    "    #fourth qustion\n",
    "    \n",
    "    wq4=t.Label(work3main,text=\"  D. The liquid metal is ?\" ,font=('Arial',15))\n",
    "    wq4.place(x=13,y=295)\n",
    "    \n",
    "    w41=t.Label(work3main,text='1. Bismuth',font=('Georgia',15))\n",
    "    w41.place(x=30,y=340)\n",
    "    \n",
    "    w42=t.Label(work3main,text='2. Magnesium',font=('Georgia',15))\n",
    "    w42.place(x=170,y=340)\n",
    "    \n",
    "    w43=t.Label(work3main,text='3. Mercury',font=('Georgia',15))\n",
    "    w43.place(x=330,y=340)\n",
    "    \n",
    "    w44=t.Label(work3main,text='4. Sodium',font=('Georgia',15))\n",
    "    w44.place(x=480,y=340)\n",
    "    \n",
    "    global s4\n",
    "    s4=t.Entry(work3main)\n",
    "    s4.place(x=800,y=340,width=60,height=35)\n",
    "              \n",
    "    wq5=t.Label(work3main,text=\" E.  How many colour in rainbow  ?\" ,font=('Arial',15))\n",
    "    wq5.place(x=13,y=390)\n",
    "    \n",
    "    w51=t.Label(work3main,text='1. 3',font=('Georgia',15))\n",
    "    w51.place(x=30,y=430)\n",
    "    \n",
    "    w52=t.Label(work3main,text='2. 5',font=('Georgia',15))\n",
    "    w52.place(x=140,y=430)\n",
    "    \n",
    "    w53=t.Label(work3main,text='3. 7',font=('Georgia',15))\n",
    "    w53.place(x=280,y=430)\n",
    "    \n",
    "    w54=t.Label(work3main,text='4. 8',font=('Georgia',15))\n",
    "    w54.place(x=400,y=430)\n",
    "    \n",
    "    global s5\n",
    "    s5=t.Entry(work3main)\n",
    "    s5.place(x=800,y=430,width=60,height=35)\n",
    "    \n",
    "    wq6=t.Label(work3main,text=\" F.  Which colour of light is deviated ?\" ,font=('Arial',15))\n",
    "    wq6.place(x=13,y=490)\n",
    "    \n",
    "    w61=t.Label(work3main,text='1. Red',font=('Georgia',15))\n",
    "    w61.place(x=30,y=550)\n",
    "    \n",
    "    w62=t.Label(work3main,text='2. Blue',font=('Georgia',15))\n",
    "    w62.place(x=140,y=550)\n",
    "    \n",
    "    w63=t.Label(work3main,text='3. Violet',font=('Georgia',15))\n",
    "    w63.place(x=280,y=550)\n",
    "    \n",
    "    w64=t.Label(work3main,text='4. Green',font=('Georgia',15))\n",
    "    w64.place(x=400,y=550)\n",
    "    \n",
    "    global s6\n",
    "    s6=t.Entry(work3main)\n",
    "    s6.place(x=800,y=550,width=60,height=35)\n",
    "    \n",
    "    wq7=t.Label(work3main,text=\" G.The chemical used for cooling in refrigeration is ?\" ,font=('Arial',15))\n",
    "    wq7.place(x=13,y=610)\n",
    "    \n",
    "    w71=t.Label(work3main,text='1. Co2',font=('Georgia',15))\n",
    "    w71.place(x=30,y=660)\n",
    "    \n",
    "    w72=t.Label(work3main,text='2. NH4 OH',font=('Georgia',15))\n",
    "    w72.place(x=140,y=660)\n",
    "\n",
    "    w73=t.Label(work3main,text='3. NH4 cl',font=('Georgia'))\n",
    "    w73.place(x=280,y=660)\n",
    "    \n",
    "    w74=t.Label(work3main,text='4. Liquified ammonia',font=('Georgia',15))\n",
    "    w74.place(x=400,y=660)\n",
    "     \n",
    "    global s7\n",
    "    s7=t.Entry(work3main)\n",
    "    s7.place(x=800,y=660,width=60,height=35)\n",
    "    \n",
    "    subbut=t.Button(work3main,text=\"Submit Test\",font=('Chaparral Pro Light',20),command=svalid)\n",
    "    subbut.place(x=1000,y=660,width=200,height=45)\n",
    "   \n",
    "    work3main.mainloop()\n",
    "    \n",
    "def clickme2():\n",
    "    messagebox.showinfo(\"SUBMIT\",'CHECKING YOUR RESULT FOR NEXT TEST IF PASS NEXT TEST IS STARTED AND FAIL AUTOMATIVALLY GO FOR LOGIN PAGE')\n",
    "    svalid()\n",
    "\n",
    "def svalid():\n",
    "    st1=int(s1.get())\n",
    "    st2=int(s2.get())\n",
    "    st3=int(s3.get())\n",
    "    st4=int(s4.get())\n",
    "    st5=int(s5.get())\n",
    "    st6=int(s6.get())\n",
    "    st7=int(s7.get())\n",
    "    scount=0\n",
    "    if(st1==2):\n",
    "        scount+=1\n",
    "    if(st2==1):\n",
    "        scount+=1\n",
    "    if(st3==4):\n",
    "        scount+=1\n",
    "    if(st4==3):\n",
    "        scount+=1\n",
    "    if(st5==3):\n",
    "        scount+=1\n",
    "    if(st6==1):\n",
    "        scount+=1\n",
    "    if(st7==3):\n",
    "        scount+=1\n",
    "    if(scount>4):\n",
    "        print(\"Pass\")\n",
    "        welcome_page()\n",
    "    else:\n",
    "        print(\"fail\")\n",
    "        login() \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "a\n",
      "a\n",
      "1\n",
      "1\n",
      "success\n",
      "4\n",
      "1\n",
      "3\n",
      "2\n",
      "1\n",
      "1\n",
      "3\n",
      "fail\n",
      "3\n"
     ]
    }
   ],
   "source": [
    "welcome_page()\n",
    "#login()\n",
    "#signup()\n",
    "#gkwork()\n",
    "#mtwork()\n",
    "#swork()\n",
    "#home()\n",
    "#view()\n",
    "#change_password()\n",
    "#change_email()\n",
    "#change_mobile()\n",
    "#view_report()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import time\n",
    "while True:\n",
    "    uin= input (\">> \")\n",
    "    try:\n",
    "        when_to_stop = abs(int(uin))\n",
    "    except KeyboardInterrupt:\n",
    "        break;\n",
    "    except:\n",
    "        print(\"Not a number!\")\n",
    "        \n",
    "    while when_to_stop > 0:\n",
    "        m,s= divmod(when_to_stop,60)\n",
    "        h,m = divmod(m,60)\n",
    "        time_left = str(h).zfill(2) + \":\" + str(m).zfill(2) + \":\" + str(s).zfill(2)\n",
    "        print(time_left + \"\\r\",end=\"\")\n",
    "        time.sleep(1)\n",
    "        when_to_stop-=1\n",
    "        \n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import sys\n",
    "from tkinter import *\n",
    "import time\n",
    "def tick():\n",
    "    time_string = time.strftime(\"%H:%M:%S\")\n",
    "    clock.config(text=time_string)\n",
    "    clock.after(200,tick)\n",
    "    \n",
    "root=Tk()\n",
    "clock = Label(root,font=(\"times\",200,\"bold\"),bg=\"green\")\n",
    "clock.grid(row=0,column=1)\n",
    "tick()\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.3"
  },
  "widgets": {
   "application/vnd.jupyter.widget-state+json": {
    "state": {},
    "version_major": 2,
    "version_minor": 0
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
